    name: Run Python Script

    on:
      push:
        branches:
          - main # Trigger on pushes to the main branch
      workflow_dispatch: # Allows manual triggering from the GitHub UI

    jobs:
      run-script:
        runs-on: ubuntu-latest # Specify the operating system for the runner

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4 # Action to check out your repository code

          - name: Set up Python
            uses: actions/setup-python@v5 # Action to set up a Python environment
            with:
              python-version: '3.12' # Specify the desired Python version

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install pyyaml

          - name: Execute Python script
            run: python ./src/python_test.py # Command to run your Python script
